services:
  mongo:
    image: mongo:7
    container_name: pla-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - pla-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: pla-server
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://pla-mongo:27017/passwordless-auth
      - APP_URL=http://localhost:5173
      - API_URL=http://localhost:4000
      - PORT=4000
      - NODE_ENV=development
    volumes:
      - ./server/src:/app/src
    ports:
      - "4000:4000"
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - pla-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: pla-client
    environment:
      - VITE_API_URL=http://localhost:4000
    ports:
      - "5173:5173"
    depends_on:
      server:
        condition: service_healthy
    networks:
      - pla-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mongo_data:

networks:
  pla-network:
    driver: bridge
